# Generated by Django 3.2 on 2021-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20210416_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Post_Category',
        ),
    ]
